version: '3.6'

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    ports: ## replace with expose to avoid firewall bypass
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    deploy:
      replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    ports: ## replace with expose to avoid firewall bypass
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
      - SERVER_BASEPATH=/kibana
    depends_on:
      - "elastic"
    deploy:
      replicas: 1

  nginx-proxy:
    image: nginx:1.21-alpine
    ports:
      - 80:80
    volumes:
      - ${PWD}/nginx-default.config:/etc/nginx/conf.d/default.conf
    depends_on:
      - "elastic"
      - "kibana"
    deploy:
      replicas: 1

volumes:
  elastic_data:
