---
apiVersion: v1
kind: Service
metadata:
  name: simple-rest
spec:
  selector:
    app: simple-rest
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: simple-rest
spec:
  selector: 
    matchLabels:
      app: simple-rest
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-rest
    spec:
      containers:
       - name: simple-rest
         image: service-simple-rest:1.0.0-SNAPSHOT
         imagePullPolicy: Never
         ports:
          - name: http
            containerPort: 8080
         resources:
           limits:
             memory: 512Mi
             cpu: 2000m
           requests:
             memory: 256Mi
             cpu: 2000m

