version: '2'

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    environment:
      - node.name=es01
      #- cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #volumes:
    #  - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
    networks:
      - elastic
    #volumes:
    #  - ./kibana.yml:/usr/share/kibana/config/kibana.yml

networks:
  elastic:
    driver: bridge
